# Generated by Django 5.1.7 on 2025-03-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='media/faces/'),
        ),
    ]
