# Generated by Django 5.1.7 on 2025-03-20 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='faces/'),
        ),
    ]
