# Generated by Django 5.1.7 on 2025-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
